version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries:
  - en
  - technical
  - python
words:
  - excepthook
  - levelname
  - FURB
ignoreWords: []
import: []
ignoreRegExpList:
 - /[A-Z][a-z]{3,}/gm
